@startuml
!theme crt-green
' !theme crt-amber

user |o--o| merchant
user |o--o| customer

merchant }o--o{ goods
note on link
    sale
end note

customer }o--o{ goods
note on link
    purchase
end note

@enduml